#!/usr/bin/env python3

import argparse
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path

POST_RE = re.compile(
    r"^POST\s+rows=(?P<rows>\d+)\s+cols=(?P<cols>\d+)\s+nbytes=(?P<nbytes>\d+)\s+"
    r"start_lba=(?P<start_lba>\d+)\s+nblocks=(?P<nblocks>\d+)\s+host_addr=.*$"
)


@dataclass
class PostRecord:
    line_no: int
    rows: int
    cols: int
    nbytes: int
    start_lba: int
    nblocks: int


def parse_trace(path: Path) -> tuple[list[PostRecord], list[str]]:
    records: list[PostRecord] = []
    parse_errors: list[str] = []

    with path.open("r", encoding="utf-8") as f:
        for i, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue

            m = POST_RE.match(line)
            if not m:
                parse_errors.append(f"line {i}: malformed trace line: {line}")
                continue

            records.append(
                PostRecord(
                    line_no=i,
                    rows=int(m.group("rows")),
                    cols=int(m.group("cols")),
                    nbytes=int(m.group("nbytes")),
                    start_lba=int(m.group("start_lba")),
                    nblocks=int(m.group("nblocks")),
                )
            )

    return records, parse_errors


def validate_records(records: list[PostRecord], block_size: int) -> list[str]:
    issues: list[str] = []

    for rec in records:
        if rec.rows <= 0 or rec.cols <= 0:
            issues.append(
                f"line {rec.line_no}: invalid tensor shape (rows={rec.rows}, cols={rec.cols})"
            )

        if rec.nbytes <= 0:
            issues.append(
                f"line {rec.line_no}: nbytes must be > 0 (got {rec.nbytes})"
            )

        if rec.nblocks <= 0:
            issues.append(
                f"line {rec.line_no}: nblocks must be > 0 (got {rec.nblocks})"
            )

        expected_nblocks = int(math.ceil(rec.nbytes / block_size))
        if rec.nblocks != expected_nblocks:
            issues.append(
                f"line {rec.line_no}: nblocks mismatch (got {rec.nblocks}, expected {expected_nblocks}, nbytes={rec.nbytes}, block_size={block_size})"
            )

        if rec.nblocks > 0:
            min_bytes = (rec.nblocks - 1) * block_size + 1
            max_bytes = rec.nblocks * block_size
            if not (min_bytes <= rec.nbytes <= max_bytes):
                issues.append(
                    f"line {rec.line_no}: nbytes out of block coverage range (nbytes={rec.nbytes}, valid_range=[{min_bytes}, {max_bytes}])"
                )

    for i in range(1, len(records)):
        prev = records[i - 1]
        cur = records[i]
        if cur.start_lba <= prev.start_lba:
            issues.append(
                f"line {cur.line_no}: start_lba not strictly increasing (prev line {prev.line_no} start_lba={prev.start_lba}, current start_lba={cur.start_lba})"
            )

        expected_start = prev.start_lba + prev.nblocks
        if cur.start_lba != expected_start:
            issues.append(
                f"line {cur.line_no}: non-contiguous allocation (expected start_lba={expected_start} from prev line {prev.line_no}, got {cur.start_lba})"
            )

    # Defensive check: there should be no overlapping LBA ranges even if order changes.
    ranges = sorted(records, key=lambda r: r.start_lba)
    for i in range(1, len(ranges)):
        prev = ranges[i - 1]
        cur = ranges[i]
        prev_end = prev.start_lba + prev.nblocks
        if cur.start_lba < prev_end:
            issues.append(
                f"line {cur.line_no}: overlapping LBA range (prev line {prev.line_no} end_lba={prev_end - 1}, current start_lba={cur.start_lba})"
            )

    return issues


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate AIF POST fake trace: nblocks formula and start_lba monotonicity."
    )
    parser.add_argument(
        "trace_path",
        type=Path,
        help="Path to trace file generated by GGML_AIF_FAKE_TRACE",
    )
    parser.add_argument(
        "--block-size",
        type=int,
        default=4096,
        help="Block size used by nblocks calculation (default: 4096)",
    )
    parser.add_argument(
        "--max-issues",
        type=int,
        default=50,
        help="Maximum number of issue lines to print (default: 50)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.block_size <= 0:
        print("FAIL: --block-size must be > 0")
        return 2

    if args.max_issues <= 0:
        print("FAIL: --max-issues must be > 0")
        return 2

    if not args.trace_path.exists():
        print(f"FAIL: trace file not found: {args.trace_path}")
        return 2

    records, parse_errors = parse_trace(args.trace_path)

    if len(records) == 0:
        print(f"FAIL: no valid POST records found in {args.trace_path}")
        for err in parse_errors:
            print(f"  - {err}")
        return 2

    issues = []
    issues.extend(parse_errors)
    issues.extend(validate_records(records, args.block_size))

    if issues:
        print("FAIL")
        print(f"records={len(records)} issues={len(issues)}")
        for issue in issues[:args.max_issues]:
            print(f"  - {issue}")
        if len(issues) > args.max_issues:
            print(f"  - ... truncated {len(issues) - args.max_issues} additional issues")
        return 1

    first_lba = records[0].start_lba
    last_end_lba = records[-1].start_lba + records[-1].nblocks
    total_bytes = sum(r.nbytes for r in records)
    total_blocks = sum(r.nblocks for r in records)

    print("PASS")
    print(f"records={len(records)}")
    print(
        "checked: "
        f"nblocks=ceil(nbytes/{args.block_size}), "
        "shape/size validity, block coverage range, "
        "start_lba strictly increasing, contiguous placement, non-overlap"
    )
    print(
        f"summary: first_lba={first_lba}, end_lba_exclusive={last_end_lba}, "
        f"total_blocks={total_blocks}, total_bytes={total_bytes}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
